---
version: '3'

vars:
    TF_MODULE: '{{default "default" .TF_MODULE}}'
    TF_VARS_FILE: '{{default "fixtures.tfvars" .TF_VARS_FILE}}'
    TF_BACKEND_CONFIG: '{{default "config/remote.config" .TF_BACKEND_CONFIG}}'

    AWS_ACCESS_KEY_ID: '{{default "" .AWS_ACCESS_KEY_ID}}'
    AWS_SECRET_ACCESS_KEY: '{{default "" .AWS_SECRET_ACCESS_KEY}}'
    AWS_DEFAULT_REGION: '{{default "us-east-1" .AWS_DEFAULT_REGION}}'

includes:
    common:
        taskfile: ./../DevEx/taskfile/TaskFile.common.yml

    tf:
        taskfile: ./../DevEx/taskfile/TaskFile.terraform.yml

tasks:
    clean:
        desc: Clean all the .terraform directories
        cmds:
            - task: common:clean

    init:
        deps: [clean]
        cmds:
            - task: tf:init
              vars: {TF_WORKING_DIR: '{{.TF_MODULE}}'}

    plan:
        deps: [clean]
        cmds:
            - task: tf:plan
              vars: {TF_WORKING_DIR: '{{.TF_MODULE}}'}

    ci:
        deps: [clean]
        cmds:
            - task: tf:validate
              vars: {TF_WORKING_DIR: '{{.TF_MODULE}}'}
            - task: tf:lint
              vars: {TF_WORKING_DIR: '{{.TF_MODULE}}'}
            - task: tf:docs
              vars: {TF_WORKING_DIR: '{{.TF_MODULE}}'}
            - task: tf:fmt-fix
              vars: {TF_WORKING_DIR: '{{.TF_MODULE}}'}

    docs:
        deps: [clean]
        cmds:
            - task: tf:docs
              vars: {TF_WORKING_DIR: '{{.TF_MODULE}}'}
