---
run:
  timeout: 10m

# Linter settings
linters-settings:
  govet:
    enable-all: true
  gocyclo:
    min-complexity: 20
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - hugeParam
      - commentedOutCode

# Enabled linters
linters:
  disable-all: false
  enable:
    # Core linters for reliability
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

    # Style and complexity linters
    - gofmt
    - gocyclo
    - goconst
    - gocritic
    - revive

    # Security linters (important for Terratest)
    - gosec
    - bodyclose

# Issue handling rules
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - gocritic
    - linters:
        - staticcheck
      text: "SA1019:"
  exclude-dirs:
    - vendor
    - go/pkg/mod
  exclude-files:
    - '.*\.pb\.go'
    - '.*_generated\.go'

# Output configuration
output:
  sort-results: true
  print-issued-lines: true
  print-linter-name: true
