---
repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-json
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: pretty-format-json
        args: [--autofix]

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: git-check # Configure in .gitattributes
      - id: git-dirty # Configure in .gitignore
      - id: script-must-have-extension


  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.23
    hooks:
      - id: shellcheck

  - repo: https://github.com/mineiros-io/pre-commit-hooks
    rev: v0.5.1
    hooks:
      - id: terraform-fmt
        files: \.(tf|hcl)$
      - id: terraform-validate
        files: \.(tf|hcl)$

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
        files: ^tests/(.*/)*.*\.go$
      - id: go-mod-tidy
        files: ^tests/(.*/)*.*\.go$

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.2
    hooks:
      - id: terraform_tflint
        name: Terraform tflint
        entry: >
          sh -c '
          CONFIGS=$(find . -maxdepth 3 \( -path "./modules/*" -o -path "./examples/*" \) -type f -name ".tflint.hcl" -print0 |
          xargs -0 -I{} sh -c "echo {}";
          find . -maxdepth 1 -type f -name ".tflint.hcl" -print0 |
          xargs -0 -I{} sh -c "echo {}";
          ) || true;

          if [ -n "$CONFIGS" ]; then
            for config in $CONFIGS; do
              echo "Initializing tflint with config: $config";
              tflint --init --config="$config" "$(dirname "$config")";
            done
          else
            echo "No .tflint.hcl configuration found";
          fi'
        files: \.(tf|hcl)$
        language: system
