---
repos:
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.33.0
      hooks:
          - id: yamllint

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: trailing-whitespace
          - id: check-added-large-files
          - id: check-case-conflict
          - id: check-merge-conflict
          - id: check-shebang-scripts-are-executable
          - id: check-symlinks
          - id: check-toml
          - id: check-yaml
          - id: check-json
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: pretty-format-json
            args: [--autofix]

    - repo: https://github.com/jumanjihouse/pre-commit-hooks
      rev: 3.0.0
      hooks:
          - id: git-check # Configure in .gitattributes
          - id: git-dirty # Configure in .gitignore
          - id: script-must-have-extension


    - repo: https://github.com/gruntwork-io/pre-commit
      rev: v0.1.23
      hooks:
          - id: shellcheck

    - repo: https://github.com/mineiros-io/pre-commit-hooks
      rev: v0.5.0
      hooks:
          - id: terraform-fmt
            files: ^(modules|examples)/.+(\.tf|\.hcl)$
          - id: terraform-validate
            files: ^(modules|examples)/.+(\.tf|\.hcl)$

    - repo: https://github.com/mineiros-io/pre-commit-hooks
      rev: v0.5.0
      hooks:
          - id: terraform-fmt
            files: ^tests/.+\.tf$
          - id: terraform-validate
            files: ^tests/.+\.tf$

    - repo: https://github.com/dnephin/pre-commit-golang
      rev: v0.5.1
      hooks:
          - id: go-fmt
            files: ^tests/(.*/)*.*\.go$
          - id: go-mod-tidy
            files: ^tests/(.*/)*.*\.go$

    - repo: https://github.com/igorshubovych/markdownlint-cli
      rev: v0.37.0
      hooks:
          - id: markdownlint-fix
            args: [.]

    - repo: https://github.com/antonbabenko/pre-commit-terraform
      rev: v1.83.6
      hooks:
          - id: terraform_tflint
            files: ^(modules|examples)/.+(\.tf|\.hcl)$
            args:
                - --args=--config=.tflint.hcl --init

    - repo: https://github.com/tcort/markdown-link-check
      rev: v3.11.2
      hooks:
          - id: markdown-link-check
            args:
                - -q
                - --config=.markdown-link-check.json

    - repo: https://github.com/terraform-docs/terraform-docs
      rev: v0.16.0
      hooks:
          - id: terraform-docs-go
            files: ^(modules|examples)/.*/.*\.(tf|hcl)$
            entry: sh -c 'for d in modules/* examples/*; do [ -d "$d" ] && [ -f "$d/.terraform-docs.yml" ] && terraform-docs markdown --config "$d/.terraform-docs.yml"
                --output-file "$d/README.md" --output-mode inject "$d" || echo "Skipping $d, no .terraform-docs.yml found"; done'
            language: system

    - repo: https://github.com/golangci/golangci-lint
      rev: v1.55.2
      hooks:
          - id: golangci-lint
            args: [--config=.golangci.yml]
            entry: bash -c 'for d in tests/*/integration tests/*/unit; do if [ -d "$d" ]; then echo "Running golangci-lint in $d"; (cd "$d" && golangci-lint
                run --config=../../../.golangci.yml ./...); fi; done'
