---

yaml-files:
    - '*.yaml'
    - '*.yml'
    - .yamllint

ignore: |
    /.github/METADATA.yaml

rules:
    braces: enable
    brackets: enable
    colons: enable
    commas: enable
    comments:
        level: warning
    document-start: disable
    empty-lines:
        max: 2
        level: warning
    indentation:
        spaces: 4
        indent-sequences: true
    key-duplicates: enable
    line-length:
        max: 120
        level: warning
    new-line-at-end-of-file: enable
    trailing-spaces: enable
    truthy:
        level: warning
