---

yaml-files:
    - '*.yaml'
    - '*.yml'
    - .yamllint

ignore: |
    /.github/METADATA.yaml
    vendor/
    node_modules/
    dist/

rules:
    braces: enable
    brackets: enable
    colons: enable
    commas: enable
    comments:
        level: error
        require-starting-space: true
    document-start:
        level: warning
    empty-lines:
        max: 2
        level: warning
    indentation:
        spaces: 4
        indent-sequences: true
    key-duplicates: enable
    line-length:
        max: 120
        level: error
    new-line-at-end-of-file: enable
    trailing-spaces: enable
    truthy:
        level: error
        allowed-values: ['true', 'false', 'yes', 'no']
