---
version: '3'
env:
    ENV: '{{.ENV}}'

vars:
    # These are constants.
    # -------------------------------
    TFVARS_DIR_RECIPES: '{{default "fixtures" .TFVARS_DIR_RECIPES}}'
    TEST_DIR: '{{default "tests" .TEST_DIR}}'
    TEST_TYPE_UNIT: '{{default "unit" .TEST_TYPE_UNIT}}'
    TERRAFORM_MODULES_DIR: '{{default "modules" .TERRAFORM_MODULES_DIR}}'
    TERRAFORM_RECIPES_DIR: '{{default "examples" .TERRAFORM_RECIPES_DIR}}'
    # -------------------------------
    tfmod: '{{default "default" .tfmod}}'
    tfvars: '{{default "fixtures.tfvars" .VARS}}'
    recipe: '{{default "basic" .recipe}}'

dotenv: ['.env.{{.ENV}}.aws', '.env.{{.ENV}}.terraform', '.env.{{.ENV}}.terragrunt', '.env.{{.ENV}}']

includes:
    common:
        taskfile: ./taskfiles/taskfile.common.yml
    precommit:
        taskfile: ./taskfiles/taskfile.precommit.yml
    tf:
        taskfile: ./taskfiles/Taskfile.terraform.yml
    golang:
        taskfile: ./taskfiles/Taskfile.go.yml
    iac:
        taskfile: ./taskfiles/Taskfile.iac.yml

tasks:
  # ***********************
  # Common tasks
  # ***********************
    default:
        cmds:
            - task: common:default

    pc-init:
        desc: Initialize and install required hooks
        cmds:
            - task: precommit:hooks-init

    pc-run:
        desc: Run all the hooks described in the .pre-commit-config.yaml file
        cmds:
            - task: precommit:hooks-run
    # ****************************************************
    # Go Tasks
    # ****************************************************
    go-tidy:
        desc: Tidy go modules
        cmds:
            - echo "===========> Run go tidy against code in directory {{.TEST_DIR}}/{{.tfmod}}"
            - task: golang:go-tidy
              vars: {mod: '{{.TEST_DIR}}/{{.tfmod}}'}
    go-fmt:
        desc: Run go fmt against code
        dir: ./{{.TEST_DIR}}/{{.MODULE}}/{{.TEST_TYPE}}
        cmds:
            - echo "===========> Run go fmt against code in directory {{.TEST_DIR}}/{{.tfmod}}"
            - task: golang:go-fmt
              vars: {mod: '{{.TEST_DIR}}/{{.tfmod}}'}
    go-vet:
        desc: Run go vet against code
        dir: ./{{.TEST_DIR}}/{{.MODULE}}/{{.TEST_TYPE}}
        cmds:
            - echo "===========> Run go vet against code in directory {{.TEST_DIR}}/{{.tfmod}}"
            - task: golang:go-vet
              vars: {mod: '{{.TEST_DIR}}/{{.tfmod}}'}
    go-lint:
        desc: Run go lint against code
        dir: ./{{.TEST_DIR}}/{{.MODULE}}/{{.TEST_TYPE}}
        cmds:
            - echo "===========> Run go lint against code in in directory {{.TEST_DIR}}/{{.tfmod}}"
            - task: golang:go-lint
              vars: {mod: '{{.TEST_DIR}}/{{.tfmod}}'}
    go-style:
        desc: Code style -> fmt,vet,lint
        deps: [go-fmt, go-vet, go-lint]

    go-test:
        desc: Run unit test-data
        dir: ./{{.TEST_DIR}}/{{.MODULE}}/{{.TEST_TYPE}}
        cmds:
            - echo "===========> Run unit tests in directory {{.TEST_DIR}}/{{.tfmod}}"
            - task: golang:go-test
              vars: {mod: '{{.TEST_DIR}}/{{.tfmod}}'}
    go-ci:
        desc: Run all the test-data and code checks
        dir: ./{{.TEST_DIR}}/{{.MODULE}}/{{.TEST_TYPE}}
        cmds:
            - task: go-style
              var: {mod: '{{.TEST_DIR}}/{{.tfmod}}'}
            - task: go-tidy
              var: {mod: '{{.TEST_DIR}}/{{.tfmod}}'}
            - task: go-test-data
              var: {mod: '{{.TEST_DIR}}/{{.tfmod}}'}
#            - task: go-build
#              var: {mod: '{{.TEST_DIR}}/{{.tfmod}}'}

  # ***********************
  # Terraform task (modules)
  # (These tasks are used to run terraform commands in the examples directory)
  # ***********************
    tf-clean:
        desc: Clean all the terraform modules and recipes from their residual .terraform folders
        cmds:
            - task: iac:clean-tf

    tg-clean:
        desc: Clean all the terraform modules and recipes from their residual .terragrunt-cache folders
        cmds:
            - task: iac:clean-tg

    tf-init:
        desc: Initialize the terraform module
        cmds:
            - task: common:clean
            - task: tf:init
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_MODULES_DIR}}/{{.tfmod}}'}

    tf-plan:
        desc: In the terraform module, execute a terraform plan
        cmds:
            - task: common:clean
            - task: tf:init
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_MODULES_DIR}}/{{.tfmod}}'}
            - task: tf:plan
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_MODULES_DIR}}/{{.tfmod}}', vars: '{{.tfvars}}'}

    tf-apply:
        desc: In the terraform module, execute a terraform apply
        cmds:
            - task: common:clean
            - task: tf:init
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_MODULES_DIR}}/{{.tfmod}}'}
            - task: tf:apply
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_MODULES_DIR}}/{{.tfmod}}', TF_VARS_FILE: '{{.tfvars}}'}

    tf-destroy:
        desc: In the terraform module, execute a terraform destroy
        cmds:
            - task: common:clean
            - task: tf:init
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_MODULES_DIR}}/{{.tfmod}}'}
            - task: tf:destroy
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_MODULES_DIR}}/{{.tfmod}}', TF_VARS_FILE: '{{.tfvars}}'}

    tf-ci:
        desc: Run CI tasks for the terraform modules as part of the 'test-data' directory
        cmds:
            - task: common:clean
            - task: tf:init
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_MODULES_DIR}}/{{.tfmod}}'}
            - task: tf:validate
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_MODULES_DIR}}/{{.tfmod}}'}
            - task: tf:fmt-fix
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_MODULES_DIR}}/{{.tfmod}}'}
            - task: tf:lint
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_MODULES_DIR}}/{{.tfmod}}'}
            - task: tf:docs
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_MODULES_DIR}}/{{.tfmod}}'}


    tf-upgrade:
        desc: Run the terraform init upgrade in all available modules, and recipes.
        cmds:
            - task: common:clean
            - task: tf:upgrade-modules
              vars: {TF_MODULES_DIR: '{{.TERRAFORM_MODULES_DIR}}'}
            - task: tf:upgrade-recipes
              vars: {TF_RECIPES_DIR: '{{.TERRAFORM_RECIPES_DIR}}'}

    tf-lint:
        desc: Run terraform lint
        cmds:
            - task: common:clean
            - task: tf:lint
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_MODULES_DIR}}/{{.tfmod}}'}

    tf-lint-all:
        desc: Run terraform lint across all modules, and recipes
        cmds:
            - task: common:clean
            - task: tf:lint
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_MODULES_DIR}}/{{.tfmod}}'}
            - task: tf:lint
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_RECIPES_DIR}}/{{.tfmod}}/{{.recipe}}'}

    tf-docs:
        desc: Generate terraform docs
        cmds:
            - task: common:clean
            - task: tf:docs
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_MODULES_DIR}}/{{.tfmod}}'}


    tf-docs-all:
        desc: Generate terraform docs for a set of modules and/or recipes
        cmds:
            - task: common:clean
            - task: tf:doc-modules
              vars: {TF_MODULES_DIR: '{{.TERRAFORM_MODULES_DIR}}'}
            - task: tf:doc-recipes
              vars: {TF_RECIPES_DIR: '{{.TERRAFORM_RECIPES_DIR}}'}

    recipe-init:
        desc: Initialize the terraform module
        cmds:
            - task: tf:init
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_RECIPES_DIR}}/{{.tfmod}}/{{.recipe}}'}

    recipe-lint:
        desc: Lint the terraform module's recipe
        cmds:
            - task: common:clean
            - task: tf:lint
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_RECIPES_DIR}}/{{.tfmod}}/{{.recipe}}'}

    recipe-plan:
        desc: In the terraform module, execute a terraform plan
        cmds:
            - task: common:clean
            - task: tf:init
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_RECIPES_DIR}}/{{.tfmod}}/{{.recipe}}'}
            - task: tf:plan
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_RECIPES_DIR}}/{{.tfmod}}/{{.recipe}}', TF_VARS_FILE: 'fixtures/{{.tfvars}}'}

    recipe-apply:
        desc: In the terraform module, execute a terraform apply
        cmds:
            - task: tf:init
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_RECIPES_DIR}}/{{.MODULE}}/{{.recipe}}'}
            - task: tf:apply
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_RECIPES_DIR}}/{{.MODULE}}/{{.recipe}}', TF_VARS_FILE: 'fixtures/{{.tfvars}}'}

    recipe-destroy:
        desc: In the terraform module, execute a terraform destroy
        cmds:
            - task: tf:init
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_RECIPES_DIR}}/{{.MODULE}}/{{.recipe}}'}
            - task: tf:destroy
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_RECIPES_DIR}}/{{.MODULE}}/{{.recipe}}', TF_VARS_FILE: 'fixtures/{{.tfvars}}'}


    recipe-lifecycle:
        desc: In the terraform module, execute a terraform lifecycle
        cmds:
            - task: tf:init
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_RECIPES_DIR}}/{{.MODULE}}/{{.recipe}}'}
            - task: tf:plan
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_RECIPES_DIR}}/{{.MODULE}}/{{.recipe}}', TF_VARS_FILE: 'fixtures/{{.tfvars}}'}
            - task: tf:apply
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_RECIPES_DIR}}/{{.MODULE}}/{{.recipe}}', TF_VARS_FILE: 'fixtures/{{.tfvars}}'}
            - task: tf:destroy
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_RECIPES_DIR}}/{{.MODULE}}/{{.recipe}}', TF_VARS_FILE: 'fixtures/{{.tfvars}}'}

    recipe-ci:
        desc: Run CI tasks for the terraform modules as part of the 'test-data' directory
        cmds:
            - task: common:clean
            - task: tf:init
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_RECIPES_DIR}}/{{.tfmod}}/{{.recipe}}'}
            - task: tf:validate
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_RECIPES_DIR}}/{{.tfmod}}/{{.recipe}}'}
            - task: tf:fmt-fix
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_RECIPES_DIR}}/{{.tfmod}}/{{.recipe}}'}
            - task: tf:lint
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_RECIPES_DIR}}/{{.tfmod}}/{{.recipe}}'}
            - task: tf:docs
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_RECIPES_DIR}}/{{.tfmod}}/{{.recipe}}'}

    recipe-docs:
        desc: Generate terraform docs
        cmds:
            - task: common:clean
            - task: tf:docs
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_RECIPES_DIR}}/{{.tfmod}}/{{.recipe}}'}

    iac-ci:
        desc: Run CI against modules and its recipes
        cmds:
            - task: common:clean
            - task: tf:init
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_RECIPES_DIR}}/{{.tfmod}}/{{.recipe}}'}
            - task: tf:validate
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_RECIPES_DIR}}/{{.tfmod}}/{{.recipe}}'}
            - task: tf:fmt-fix
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_RECIPES_DIR}}/{{.tfmod}}/{{.recipe}}'}
            - task: tf:lint
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_RECIPES_DIR}}/{{.tfmod}}/{{.recipe}}'}
            - task: tf:docs
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_RECIPES_DIR}}/{{.tfmod}}/{{.recipe}}'}
            - task: common:clean
            - task: tf:init
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_MODULES_DIR}}/{{.tfmod}}'}
            - task: tf:validate
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_MODULES_DIR}}/{{.tfmod}}'}
            - task: tf:fmt-fix
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_MODULES_DIR}}/{{.tfmod}}'}
            - task: tf:lint
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_MODULES_DIR}}/{{.tfmod}}'}
            - task: tf:docs
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_MODULES_DIR}}/{{.tfmod}}'}
