---
name: Feature Request
description: Propose improvements for the Terraform Module Template
title: "feat: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing to the Terraform Module Template.

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Select the primary component this feature impacts
      options:
        - Module Core (`modules/default`)
        - Module Example (`examples/...`)
        - Test Suite (`tests/...`)
        - Documentation (`docs/...`)
        - CI/CD Workflow (`.github/workflows/...`)
        - Tooling (`Justfile`, `flake.nix`, scripts)
        - Cross-cutting Concern
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement / Current Behavior
      description: "Describe the specific limitation, challenge, or current behavior you'd like to see improved. Why is this a problem?"
      placeholder: "What problem are you trying to solve? E.g., I'm always frustrated when [...]"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution / Desired Behavior
      description: "Outline your proposed feature, improvement, or the desired behavior. How would this solve the problem?"
      placeholder: |
        - Key functionality/behavior change:
        - Implementation approach (if any):
        - Configuration modifications (if any):
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases & Benefits
      description: "Describe specific scenarios where this feature provides value. What are the benefits?"
      placeholder: |
        1. Primary Use Case: ... (Benefit: ...)
        2. Secondary Use Case: ... (Benefit: ...)
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Suggested Priority
      description: How critical or valuable do you consider this feature?
      options:
        - High (Critical for workflow / High value)
        - Medium (Significant improvement / Medium value)
        - Low (Nice to have / Lower value)
    validations:
      required: true

  - type: textarea
    id: technical-considerations
    attributes:
      label: Technical Considerations (Optional)
      description: "Any compatibility, configuration impact, or other technical details. E.g., Terraform version requirements, provider compatibility."
      placeholder: |
        - Terraform version requirements:
        - Potential configuration changes:
        - Provider compatibility issues:
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered (Optional)
      description: "Have you considered any alternative solutions or workarounds? If so, please describe them and why they were not sufficient."
      placeholder: "E.g., Current workaround is X, but it's not ideal because Y."
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context (Optional)
      description: Any supplementary information, links to documentation, references, or related discussions.
      placeholder: Links to documentation, references, or related discussions
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution Guidelines
      description: By submitting this issue, you agree to follow our project's [Code of Conduct](../../CODE_OF_CONDUCT.md).
      options:
        - label: I have searched existing issues and RFCs and verified this is not a duplicate.
          required: true
        - label: I am willing to submit a Pull Request to implement this feature (optional).
          required: false
