---
formatter: markdown table

recursive:
  enabled: true
  path: .

sections:
  hide: []
  show: []

content: |-
  # {{ .Name }}

  {{ .Description }}

  ## Overview

  {{ .Header }}

  {{ if .Inputs }}
  ## Inputs

  {{ .Inputs }}
  {{ end }}

  {{ if .Outputs }}
  ## Outputs

  {{ .Outputs }}
  {{ end }}

  {{ if .Resources }}
  ## Resources

  {{ .Resources }}
  {{ end }}

output:
    file: README.md
    mode: inject
    template: |-
        <!-- BEGIN_TF_DOCS -->
        {{ .Content }}
        <!-- END_TF_DOCS -->
settings:
    anchor: true
    color: true
