---
formatter: markdown table

recursive:
  enabled: true
  path: .

sections:
  hide: []
  show:
    - inputs
    - outputs
    - resources

content: |-
  # Terraform Default Module

  ## Overview
  > **Warning:** 🚨 This module is a template and should be customized to fit your specific infrastructure needs.

  ### 🌟 Module Purpose
  This Terraform module provides a flexible and reusable infrastructure component designed to streamline your cloud resource management.

  ### 🔑 Key Features
  - **Customizable Configuration**: Easily adapt the module to your specific requirements
  - **Best Practice Implementations**: Follows industry-standard infrastructure-as-code principles
  - **Comprehensive Input Validation**: Robust variable type and constraint checking

  ### 📋 Usage Guidelines
  1. Review the available input variables
  2. Customize the module parameters to match your infrastructure needs
  3. Integrate with your existing Terraform configurations
  4. Validate and test thoroughly before production deployment

  ### 🛠 Recommended Practices
  - Always specify required variables
  - Use meaningful tags for resource tracking
  - Consider environment-specific variations
  - Implement proper access controls

  ### 🚧 Limitations and Considerations
  - Ensure compatibility with your cloud provider
  - Check regional availability of resources
  - Review pricing implications of deployed resources

  {{ .Header }}

  ## Variables

  {{ .Inputs }}

  ## Outputs

  {{ .Outputs }}

  ## Resources

  {{ .Resources }}

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

settings:
  anchor: true
  color: true
  description: true
  escape: true
  header: true
  html: true
  indent: 2
  required: true
  sensitive: true
  type: true
