---
name: Unit & Integration tests

on:
    pull_request:
        types: [opened, edited, synchronize]

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: us-east-1

jobs:
    unit-tests:
        name: Unit tests
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - module: default
                      type: unit

        defaults:
            run:
                working-directory: tests/${{ matrix.module }}/${{ matrix.type }}

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-go@v3
              with:
                  go-version: 1.19
            - run: |
                  go test -v -count=1 -timeout 30m -parallel 128 -run ./...


    integration-tests:
        name: Integration tests
        runs-on: ubuntu-latest
        needs: [unit-tests]
        strategy:
            fail-fast: false
            matrix:
                include:
                    - module: default
                      type: integration

        defaults:
            run:
                working-directory: tests/${{ matrix.module }}/${{ matrix.type }}

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-go@v3
              with:
                  go-version: 1.19
            - run: |
                  go test -v -count=1 -timeout 30m -parallel 128 -run ./...
