---
name: Go Linter Terratest

on:
    workflow_dispatch:
    push:
    pull_request:

permissions:
    contents: read
    pull-requests: write

jobs:
    setup-matrix:
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{ steps.find-dirs.outputs.matrix }}
        steps:
            - uses: actions/checkout@v3
            - name: Find test directories
              id: find-dirs
              run: |
                  dirs=$(find tests -type d \( -name 'integration' -o -name 'unit' \) -exec dirname {} \; | sort -u)
                  matrix=$(echo "$dirs" | jq -R -cs 'split("\n")[:-1]')
                  echo "matrix=$matrix" > $GITHUB_ENV

    golangci:
        needs: setup-matrix
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - dir: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
        steps:
            - uses: actions/checkout@v3
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: '1.18' # Use the correct version of Go
            - name: golangci-lint
              uses: golangci/golangci-lint-action@v3
              with:
                  version: latest
                  args: --config .golangci.yml
                  working-directory: ${{ matrix.dir }}
