---
name: Go Linter Terratest

on:
    workflow_dispatch:
    push:
    pull_request:
        types: [opened, edited, synchronize]

env:
    TEST_ROOT: tests

jobs:
    setup-matrix:
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{ steps.set-matrix.outputs.matrix }}

        steps:
            - uses: actions/checkout@v4

            - name: Set matrix
              id: set-matrix
              run: |
                  DIRS=$(find ${{ env.TEST_ROOT }} -type f -name 'go.mod' -exec dirname {} \;)
                  DIRS_ARRAY=()
                  for dir in $DIRS; do
                    DIRS_ARRAY+=("$dir")
                  done
                  MATRIX_JSON=$(echo "${DIRS_ARRAY[@]}" | jq -R -s -c 'split(" ")')
                  echo "::set-output name=matrix::${MATRIX_JSON}"

    golangci:
        needs: setup-matrix
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                dir: ${{fromJson(needs.setup-matrix.outputs.matrix)}}

        steps:
            - uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: '1.21' # Adjust this to the Go version you want to use

            - name: golangci-lint
              uses: golangci/golangci-lint-action@v3
              with:
                  version: latest
                  args: --config ../../.golangci.yml
                  working-directory: ${{ matrix.dir }}
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  reporter: github-pr-check
