---
name: Unit & Integration tests TerraTest

on:
    workflow_dispatch:
    push:
    pull_request:
        types: [opened, edited, synchronize]

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: us-east-1

jobs:
    prepare_test_matrix:
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{ steps.set-matrix.outputs.matrix }}

        steps:
            - uses: actions/checkout@v4

            - name: Set up test matrix
              id: set-matrix
              run: |
                  TEST_DIRS=$(find tests -type d \( -path '*/integration' -o -path '*/unit' \))
                  TEST_DIRS_JSON=$(echo "$TEST_DIRS" | jq -R -s -c 'split("\n")[:-1]')
                  echo "::set-output name=matrix::${TEST_DIRS_JSON}"

    run_terratest:
        needs: prepare_test_matrix
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                test_dir: ${{fromJson(needs.prepare_test_matrix.outputs.matrix)}}

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v3
              with:
                  go-version: 1.21
            - name: Run Terratest
              run: |
                  TEST_DIR=${{ matrix.test_dir }}
                  echo "Running tests in $TEST_DIR"
                  cd "$TEST_DIR"
                  go test -v -count=1 -timeout 30m -parallel 128 -run ./...
