---
name: Terraform Plan for Changed Modules

on:
    push:
        paths:
            - modules/**
    workflow_dispatch:
    pull_request:
        types: [opened, edited, synchronize]
        paths:
            - modules/**

jobs:
    setup_matrix:
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{ steps.set-matrix.outputs.matrix }}

        steps:
            - uses: actions/checkout@v4

            - name: Find changed modules
              id: changed-modules
              if: ${{ github.event_name == 'pull_request' }}
              run: |
                  CHANGED_MODULES=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '^modules/' | awk -F/ '{print $2}' | uniq)
                  echo "Changed modules: $CHANGED_MODULES"

            - name: Set up matrix for Terraform recipes
              id: set-matrix
              run: |
                  if [ "${{ github.event_name }}" == "pull_request" ]; then
                    MODULES=$CHANGED_MODULES
                  else
                    MODULES=$(find modules -mindepth 1 -maxdepth 1 -type d -exec basename {} \;)
                  fi
                  RECIPES=()
                  for MODULE in $MODULES; do
                    MODULE_RECIPES=$(find examples/$MODULE -mindepth 1 -maxdepth 1 -type d -printf 'examples/%P\n')
                    for RECIPE in $MODULE_RECIPES; do
                      RECIPES+=("$RECIPE")
                    done
                  done
                  RECIPES_JSON=$(echo "${RECIPES[@]}" | jq -R -s -c 'split("\n")[:-1]')
                  echo "::set-output name=matrix::${RECIPES_JSON}"

    terraform_commands:
        needs: setup_matrix
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                recipe: ${{fromJson(needs.setup_matrix.outputs.matrix)}}

        steps:
            - uses: actions/checkout@v4

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Terraform Init
              run: terraform init
              working-directory: ${{ matrix.recipe }}
